### PR TITLE
Various edits to fix obvious issues

### PR DESCRIPTION
**Pull request by agentzh**
**Please do not merge this PR atm.**

This PR is now open for review and comments. I'm still pushing more changes to this branch (and this PR). Thanks!

### CODE REVIEW

**Comment by agentzh** [comment]
You're welcome to review and comment on my existing commits in this PR.

Just do not merge them since I'm still adding more commits to PR :)

Thanks!

**Comment by agentzh** [comment]
Let's merge this PR? :)

**Comment by membphis** [comment]
这本书是面向国内用户的，所以后面使用中文交流了。我之前误解饿，一直想着春哥全部批注完后，再回来全部修改。看来还是小步迭代吧。我将按照每个 commit 逐个修改

**Comment by membphis** [comment]
终于全部迁移成功 @moonbingbing @aifeiasdf ，有空一起校验一下，后面还有一些基础章节。家里老人在，晚上回家不能写作，单位又太忙。

**Pull request closed without merging**
